# 服务端口号
server:
  port: 8080

spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labelclocksystem?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&&allowPublicKeyRetrieval=true
    username: root
    password: '040110'
#&serverTimezone=GMT
logging:
  file:
    path: /home/log/backend
  level:
    root: error
  config: classpath:logback-spring.xml