# 默认以下配置默认会读取环境变量的值
mysql-public-host: ${MYSQL_PUBLIC_HOST:172.18.0.3}
mysql-public-port: ${MYSQL_PUBLIC_PORT:3306}
mysql-password: ${MYSQL_ROOT_PASSWORD:040110}

# 服务端口号
server:
  port: 8080

spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql-public-host}:${mysql-public-port}/labelclocksystem?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&&allowPublicKeyRetrieval=true
    username: root
    password: ${mysql-password}
#&serverTimezone=GMT
logging:
  file:
    path: /home/log/backend
  level:
    root: info
  config: classpath:logback-spring.xml